Added Grady Booch books
jordan-cutler/path-to-senior-engineer-handbook pull request #5
Opened 2023-11-26 13:56 UTC by zarya-gh

The most complete software architecture books collection

2023-11-26 14:28 UTC, jordan-cutler requested changes
Hi @zarya-gh thank you for your contribution.

I have 2 small requests.

1. The Grady Booch collection seems like a great resource. My only concern is that it isn't super curated. Do you think you could pick just a couple books from that list that you've personally read or would recommend that way someone could just direct link straight to that one without needing to do research on their own?

2. Could you explain a bit more about what the "Coders at work: Reflections on the Craft of Programming" teaches? I want to make sure it gets put in the correct category. The "Learn from the top programmers" section has a chance of only having that book in it for awhile

2023-11-26 15:43 UTC, zarya-gh commented
> Hi @zarya-gh thank you for your contribution.
> 
> I have 2 small requests.
> 
> 1. The Grady Booch collection seems like a great resource. My only concern is that it isn't super curated. Do you think you could pick just a couple books from that list that you've personally read or would recommend that way someone could just direct link straight to that one without needing to do research on their own?
> 2. Could you explain a bit more about what the "Coders at work: Reflections on the Craft of Programming" teaches? I want to make sure it gets put in the correct category. The "Learn from the top programmers" section has a chance of only having that book in it for awhile

hi, Jordan!
 Grady Booch's book collection impressed me as a whole. It showed me what depth of knowledge is required to become a truly professional at what you do. 
"Coders at work" book presents creative thinking and working habits of the most successful software engineers. It can help senior engineers to learn and improve by watching others.

2023-11-27 13:08 UTC, jordan-cutler commented on README.md
> +- [Coders at Work: Reflections on the Craft of Programming](https://www.amazon.com/gp/product/1430219483)
Would it make sense to add this in the "Software Engineer Overall" section?

It's meant for wide range of topics for software engineers but only applicable to software engineers

2023-11-27 13:08 UTC, jordan-cutler commented on README.md
> +- [Lee Atchison. Software Architecture: from developer to architect](https://www.linkedin.com/learning/software-architecture-from-developer-to-architect)
Can you help me understand the value of this course for achieving the senior level?

I checked it out briefly but it seems very short and mostly for devs switching to the architect role?

2023-11-27 13:11 UTC, jordan-cutler commented on README.md
> +- [Grady Booch collection of software architecture/design books](https://handbookofsoftwarearchitecture.com/books/)
```suggestion
- [Collection - Grady Booch software architecture/design books](https://handbookofsoftwarearchitecture.com/books/)
```

We could make this a standard pattern in the repo of starting with "Collection" so it's clear we'd be going to another collection

2023-11-27 13:13 UTC, jordan-cutler commented on README.md
> +- [O'Reilly video training series: Software Architecture](https://www.oreilly.com/software-architecture-video-training-series.html)
Think this may need a rebase off master. We can add this to the "Top courses" section.

Since I can't access it, could you share how it helped you in getting to the senior level so we have a documented reason for it if we need to refer back later on? I'd appreciate it 🙏

2023-11-27 13:13 UTC, jordan-cutler reviewed
a few comments

2023-11-27 13:31 UTC, zarya-gh commented on README.md
> +- [O'Reilly video training series: Software Architecture](https://www.oreilly.com/software-architecture-video-training-series.html)
I removed these courses for now, they are architecture related

2023-11-27 13:50 UTC, jordan-cutler approved these changes
awesome! Thanks for your patience with me :)

2023-11-27 13:50 UTC, merged